#pragma once

#ifndef _NTDDK_
#include <windows.h>

#include <winioctl.h>

#endif

#define IOCTL_KILL_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x123, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_RESUME_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x6767, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PROCESS_NOTIFICATION CTL_CODE(FILE_DEVICE_UNKNOWN, 0x456, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REGISTER_SERVICE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x67, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PROTECTED_PID CTL_CODE(FILE_DEVICE_UNKNOWN, 0x676, METHOD_BUFFERED, FILE_ANY_ACCESS)
